// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateItems implements pgx.CopyFromSource.
type iteratorForCreateItems struct {
	rows                 []CreateItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Title,
		r.rows[0].Url,
		r.rows[0].Note,
	}, nil
}

func (r iteratorForCreateItems) Err() error {
	return nil
}

func (q *Queries) CreateItems(ctx context.Context, arg []CreateItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"items"}, []string{"title", "url", "note"}, &iteratorForCreateItems{rows: arg})
}
