// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    title, url, note
) VALUES ($1, $2, $3)
RETURNING id, title, url, note, created_at, updated_at
`

type CreateItemParams struct {
	Title string
	Url   string
	Note  string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Title, arg.Url, arg.Note)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateItemsParams struct {
	Title string
	Url   string
	Note  string
}

const listItems = `-- name: ListItems :many
SELECT id, title, url, note, created_at, updated_at FROM items
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
